<wsdl:definitions
     name="InsertDataintoEMPPOC"
     targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/HelloWorld/DBPolltoDB_SOAProject/InsertDataintoEMPPOC"
     xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/HelloWorld/DBPolltoDB_SOAProject/InsertDataintoEMPPOC"
     xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
     xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/InsertDataintoEMPPOC"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
  <plt:partnerLinkType name="InsertDataintoEMPPOC_plt" >
    <plt:role name="InsertDataintoEMPPOC_role" >
      <plt:portType name="tns:InsertDataintoEMPPOC_ptt" />
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/InsertDataintoEMPPOC" schemaLocation="../Schemas/InsertDataintoEMPPOC_table.xsd" />
      </schema>
    </wsdl:types>
    <wsdl:message name="EmppocCollection_msg">
        <wsdl:part name="EmppocCollection" element="top:EmppocCollection"/>
    </wsdl:message>
    <wsdl:portType name="InsertDataintoEMPPOC_ptt">
        <wsdl:operation name="insert">
            <wsdl:input message="tns:EmppocCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
