<wsdl:definitions
     name="PollEmpDataFromDatabase"
     targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/HelloWorld/DBPolltoDB_SOAProject/PollEmpDataFromDatabase"
     xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/HelloWorld/DBPolltoDB_SOAProject/PollEmpDataFromDatabase"
     xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
     xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:pc="http://xmlns.oracle.com/pcbpel/"
     xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/PollEmpDataFromDatabase"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
  <plt:partnerLinkType name="PollEmpDataFromDatabase_plt" >
    <plt:role name="PollEmpDataFromDatabase_role" >
      <plt:portType name="tns:PollEmpDataFromDatabase_ptt" />
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/PollEmpDataFromDatabase" schemaLocation="../Schemas/PollEmpDataFromDatabase_table.xsd" />
      </schema>
    </wsdl:types>
    <wsdl:message name="EmpCollection_msg">
        <wsdl:part name="EmpCollection" element="top:EmpCollection"/>
    </wsdl:message>
    <wsdl:portType name="PollEmpDataFromDatabase_ptt">
        <wsdl:operation name="receive">
            <wsdl:input message="tns:EmpCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
